
version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka
    volumes:
      - ./templates:/app/templates
      - ./model:/app/model

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
